### ISSUE TITLE
Orthofinder installation in conflict with python3

### ISSUE THREAD

**Issue by pavlo888** [SWittouck/progenomics#4]
Hi, 

I am currently trying to install all the dependencies for Progenomics to run smoothly; however, I cannot successfully install Orthofinder since it comes in conflict with the already installed python=3.6.7.

How did you manage to install both Orthofinder and python=3.6.7? 

Cheers, 
Pablo

**Comment by JDOUBLE-U** [comment]
Hi Pablo,

I used python version 3.7 and Orthofinder works like a charm.
Hope it will also work for you.

Jan

**Comment by pavlo888** [comment]
Hi Jan,

I uninstalled Python 3.6.7 and installed Python 3.7 and then proceeded to
try installing Orthofinder. However, it seems that Orthofinder only works
with Python 2.3. This is the output I got on the terminal:

(progenomics) sam@BioInf2:~/Downloads/geneparser$ conda install orthofinder
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with
flexible solve.
Solving environment: failed with repodata from current_repodata.json, will
retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with
flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining python:  13%|█████▊                                       |
21/163 [00:00<00:00, 13124.78it/s]
Comparing specs that have this dependency:
0%|                                  | 0/2 [00:00<?, ?it/s]
F- ding shortest conflict path for python[version='>=3.7,<3.8.0a0']:
50%|▌| 1/2 [00:00<00:00, 4424.37|
-
failed
UnsatisfiableError: The following specifications were
found
to be incompatible with the existing python installation in your
environment:

Specifications:

  - orthofinder -> python=2.7
  - orthofinder -> python[version='>=2.7,<2.8.0a0']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've
asked for.
When python appears to the right, that indicates that the thing on the left
is somehow
not available for the python version you are constrained to. Note that
conda will not
change your python version to a different minor version unless you
explicitly specify
that.

The following specifications were found to be incompatible with each other:



Package pip conflicts for:
orthofinder -> python=2.7 -> pip
python=3.7 -> pip
Package wheel conflicts for:
python=3.7 -> pip -> wheel
orthofinder -> python=2.7 -> pip -> wheel
Package ca-certificates conflicts for:
python=3.7 -> openssl[version='>=1.0.2p,<1.0.3a'] -> ca-certificates
orthofinder -> python=2.7 -> ca-certificates
Package certifi conflicts for:
python=3.7 -> pip -> setuptools -> certifi[version='>=2016.09']
orthofinder -> python=2.7 -> pip -> setuptools ->
certifi[version='>=2016.09']
Package setuptools conflicts for:
orthofinder -> python=2.7 -> pip -> setuptools
python=3.7 -> pip -> setuptools

Is there anything I could do to fix this issue?

Cheers,
Pablo

**Comment by JDOUBLE-U** [comment]
You can try: conda install -c bioconda orthofinder
Hope that this works.

**Comment by SWittouck** [comment]
Hi Pablo, 

My apologies for the late reply, it seems that my notifications were not turned on for this repository. 

Have you been able to install OrthoFinder in the meantime? Otherwise, you can try to follow [these instructions](https://github.com/davidemms/OrthoFinder#installing-orthofinder); they might circumvent the problem that you are experiencing with conda. 

Let me know if it still doesn't work. 

Best regards,
Stijn

**Comment by SWittouck** [comment]
Hi Pablo, 

Your issue seems like a rather complicated one to solve. As an alternative, you could try the following: 

1) Download OrthoFinder manually from [here](https://github.com/davidemms/OrthoFinder/releases/download/2.3.7/OrthoFinder.tar.gz) and untar it by running `tar -xzf OrthoFinder.tar.gz`.
2) Before you run progenomics, make sure that the command `orthofinder` refers to the right executable by running `export progenomics=OrthoFinder-2.3.7/orthofinder`.
3) Test progenomics again.

I hope this helps. If not, let me know. 

Best,
Stijn

**Comment by pinkzong** [comment]
Hello, Pablo, I have met the same question with you before. But now I solve the problem.
https://github.com/davidemms/OrthoFinder/releases/tag/2.3.8
Remember to download the third one.
1.tar the file
tar -xzf OrthoFinder-2.3.8.tar.gz
2.enter into the file
cd OrthoFinder-2.3.8
3.install
python setup.py install

And then you can use orthofinder, hope everything is fine.
